### PR TITLE
PolyZone and Target Conversion

### LINKED ISSUE #19: [Placeholder] Polyzone and Target Conversion

### PR DESCRIPTION
**Pull request by trclassic92**
## qb-jewelery Config option to use Target or E (w/DrawTextui)

- false = E with DrawTextUi

- true = qb-target

### CODE REVIEW

**Review by bejoy980 — COMMENTED** [review]
[    c-scripting-core] Creating script environments for qb-jewelery
[    c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null.
[  script:qb-jewelery] Error loading script config.lua in resource qb-jewelery: Execution of native 000000006ccd2564 in script host failed: Argument at index 1 was null.
[  script:qb-jewelery] stack traceback:
[  script:qb-jewelery] 	[C]: in global '_in'
[  script:qb-jewelery] 	GetConvar.lua:2: in function 'GetConvar'
[  script:qb-jewelery] 	@qb-jewelery/config.lua:3: in main chunk
[    c-scripting-core] Failed to load script config.lua.
[ citizen-server-impl] Started resource qb-jewelery

**Comment by bejoy980** [comment]
What's the issue?

**Comment by trclassic92** [comment]
> [ c-scripting-core] Creating script environments for qb-jewelery [ c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null. [ script:qb-jewelery] Error loading script config.lua in resource qb-jewelery: Execution of native 000000006ccd2564 in script host failed: Argument at index 1 was null. [ script:qb-jewelery] stack traceback: [ script:qb-jewelery] [C]: in global '_in' [ script:qb-jewelery] GetConvar.lua:2: in function 'GetConvar' [ script:qb-jewelery] @qb-jewelery/config.lua:3: in main chunk [ c-scripting-core] Failed to load script config.lua. [ citizen-server-impl] Started resource qb-jewelery

Well lets see.... did you even set in your server.cfg   `setr UseTarget false` or `setr UseTarget true`

**Comment by greenbrad** [comment]
Line 109 needs to be fixed, or the config location object
local Dealer = AddBlipForCoord(Config.JewelleryLocation["coords"]['x'], Config.JewelleryLocation["coords"]['y'], Config.JewelleryLocation["coords"]['z'])

to

local Dealer = AddBlipForCoord(Config.JewelleryLocation["coords"].x, Config.JewelleryLocation["coords"].y, Config.JewelleryLocation["coords"].z)

**Comment by trclassic92** [comment]
> Line 109 needs to be fixed, or the config location object local Dealer = AddBlipForCoord(Config.JewelleryLocation["coords"]['x'], Config.JewelleryLocation["coords"]['y'], Config.JewelleryLocation["coords"]['z'])
> 
> to
> 
> local Dealer = AddBlipForCoord(Config.JewelleryLocation["coords"].x, Config.JewelleryLocation["coords"].y, Config.JewelleryLocation["coords"].z)

I'm confused about what you mean by this... because the coords are in the right location and the blip shows up at the location just fine without this change...

Preview Screenshot
Preview Screenshot

**Edit**
Also, this is how it is by default 

https://github.com/qbcore-framework/qb-jewelery/blob/c3c02f78843349f028706b85caeda45299705054/client/main.lua#L122

**Pull request merged**
