### PR TITLE
fix spelling of jewelry

### PR DESCRIPTION
**Pull request by itismejoey**
**Describe Pull request**
"Jewelry" is spelled wrong in several places, including the actual name of the resource. This fixes the spelling issues (minus the resource name).

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] 
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by ggfto — APPROVED** [review]
LGTM

**Review by ggfto — COMMENTED** [review]
Can you update this branch to latest version please?

**Comment by itismejoey** [comment]
> Can you update this branch to latest version please?

Should be all set.

**Review by ggfto — APPROVED** [review]
LGTM

**Comment by S33G** [comment]
`Jewelery` is a perfectly valid spelling in America.
Perhaps this would be good as a config option to allow users to choose between each spelling

**Review by S33G — CHANGES_REQUESTED** [review]
Spelling is ok, change not needed.
Config option encouraged

**Pull request closed without merging**
